mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
    map-underscore-to-camel-case: true
  global-config:
    db-config:
#      logic-delete-field: delFlag
      id-type: auto
#      logic-delete-value: 1
#      logic-not-delete-value: 0
    banner: off
