server:
  port: 81

#baseDir: C:\Users\lpl\Desktop\图\P站\

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/record-site?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true&nullCatalogMeansCurrent=true
    username: 2120400146
    password: 210019
  main:
    banner-mode: off
  #  banner:
  #    image:
  #      location: file:${baseDir}94030972_p0_master1200.jpg
  #      bitdepth: 8
  ##      width: 240
  #      invert: on
  #      pixelmode: block

  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 50MB
  profiles:
    active: dev
    group:
      "dev": mp,redis,oss


info:
  model: simple
  timeUnit: s
  open: true

logging:
  level:
    top.recordsite: debug
